//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string country { get; set; }
        public string passportNumber { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string summary { get; set; }
        public string school { get; set; }
        public string degree { get; set; }
        public int dateEducation { get; set; }
        public string cityEducation { get; set; }
        public string descriptionEducation { get; set; }
        public string jobTitle { get; set; }
        public string Employee { get; set; }
        public int dateWork { get; set; }
        public string cityWork { get; set; }
        public string descriptionWork { get; set; }
        public string basicSkill { get; set; }
        public string intermediateSkill { get; set; }
        public string advanceSkill { get; set; }
        public int rating { get; set; }
        public string star { get; set; }
    }
}
